<?php
namespace model\Sistemx;

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use Illuminate\Database\Eloquent\Model as CI_Model;
//use Illuminate\Database\Capsule\Manager as DB;

class GDriveCredentialModel extends CI_Model {
	
	protected $table="sys_gdrive";
	protected $fillable = [ "path_credential" , "status" , "tstatus_id" , "tstatus_status" ,	];
	const validation = [];

};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-07-04 12:04:25 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
