<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_ClientModel extends CI_Model {
   public $id;	
   const table = "sys_bot_telegram_client";
   const rules = [
	//"id_user" => "required|unique",
	//"chat_id" => "required|unique",
	//"register_date" => "required",
	//"register_time" => "required",
	"status" => "required",  
  ];
   
   
   
   function __construct(){
        parent::__construct();
   }	
	
	public function json($apiPost=null){
		if($apiPost)
			$this->datatables->injectPost($apiPost);
		
		$this->datatables->select('
			sys_bot_telegram_client.id as id,
			sys_bot_telegram_client.id_user as id_user,
			sys_bot_telegram_client.chat_id as chat_id,
			sys_bot_telegram_client.register_date as register_date,
			sys_bot_telegram_client.register_time as register_time,
			sys_bot_telegram_client.status,
			tuser.nmuser as nmuser,
			tstatus.status as tstatus,
			
			
		');
		
		$this->datatables->from('sys_bot_telegram_client');
	
		$this->datatables->join('sys_user tuser','tuser.id=sys_bot_telegram_client.id_user','LEFT'); 
	
		$this->datatables->join('sys_status tstatus','tstatus.id=sys_bot_telegram_client.status','LEFT'); 

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'sys_bot_telegram_client.id as id',
			'sys_bot_telegram_client.id_user as id_user',
			'sys_bot_telegram_client.chat_id as chat_id',
			'sys_bot_telegram_client.register_date as register_date',
			'sys_bot_telegram_client.register_time as register_time',
			'sys_bot_telegram_client.status',
			'tstatus.status as tstatus',
			'tuser.nmuser as nmuser',
			
			
		
		);
		$this->db->select($afield);
		$this->db->join('sys_user tuser','tuser.id=sys_bot_telegram_client.id_user','LEFT'); 
		$this->db->join('sys_status tstatus','tstatus.id=sys_bot_telegram_client.status','LEFT'); 

		$this->db->order_by('sys_bot_telegram_client.id', 'ASC');
		return $this->db->get('sys_bot_telegram_client')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'sys_bot_telegram_client.id as id',
			'sys_bot_telegram_client.id_user as id_user',
			'sys_bot_telegram_client.chat_id as chat_id',
			'sys_bot_telegram_client.register_date as register_date',
			'sys_bot_telegram_client.register_time as register_time',
			'sys_bot_telegram_client.status',
			'tstatus.status as tstatus',
			
			'tuser.nmuser as nmuser',
			
		
		);
		$this->db->select($afield);
		$this->db->join('sys_user tuser','tuser.id=sys_bot_telegram_client.id_user','LEFT'); 
		$this->db->join('sys_status tstatus','tstatus.id=sys_bot_telegram_client.status','LEFT'); 

		$this->db->where('sys_bot_telegram_client.id', $id);
		$this->db->order_by('sys_bot_telegram_client.id', 'ASC');
		return $this->db->get('sys_bot_telegram_client')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('sys_bot_telegram_client.id <>',$id);

		$q = $this->db->get_where('sys_bot_telegram_client', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('sys_bot_telegram_client', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('sys_bot_telegram_client.id', $id);
		$this->db->update('sys_bot_telegram_client', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('sys_bot_telegram_client.id',$data);	
	
			$this->db->delete('sys_bot_telegram_client');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-02-14 20:59:24 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
