<?php
namespace model\sys\client_register;

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use Illuminate\Database\Eloquent\Model as CI_Model;
//use Illuminate\Database\Capsule\Manager as DB;

class Bot_Telegram_ClientModel extends CI_Model {
	
	protected $table="sys_bot_telegram_client";
	protected $fillable = [ "id_user" , "chat_id" , "register_date" , "register_time" , "status" , "tuser_id" , "nmuser" , "passuser" , "opt_level" , "opt_status" , "picture" , "skin" , "tstatus_id" , "tstatus_status" ,	];
	const validation = [];

};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-02-14 20:59:24 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
