<?php
require_once APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_Tracking_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_bot_telegram_tracking_access_id	= 'ID';
		$this->sys_bot_telegram_tracking_access_chat_id	= 'CHAT_ID';
		$this->sys_bot_telegram_tracking_access_first_name	= 'FIRST_NAME';
		$this->sys_bot_telegram_tracking_access_last_name	= 'LAST_NAME';
		$this->sys_bot_telegram_tracking_access_message	= 'MESSAGE';
		$this->sys_bot_telegram_tracking_access_date	= 'DATE';
		$this->sys_bot_telegram_tracking_access_time	= 'TIME';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_chat_id	= 'chat_id';
		$this->f_first_name	= 'first_name';
		$this->f_last_name	= 'last_name';
		$this->f_message	= 'message';
		$this->f_date	= 'date';
		$this->f_time	= 'time';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			//$this->f_id	=> $this->sys_bot_telegram_tracking_access_id,
			'bot_name'			=> "BOT",
			$this->f_chat_id	=> $this->sys_bot_telegram_tracking_access_chat_id,
			$this->f_first_name	=> $this->sys_bot_telegram_tracking_access_first_name,
			$this->f_last_name	=> $this->sys_bot_telegram_tracking_access_last_name,
			$this->f_message	=> $this->sys_bot_telegram_tracking_access_message,
			$this->f_date	=> $this->sys_bot_telegram_tracking_access_date,
			$this->f_time	=> $this->sys_bot_telegram_tracking_access_time,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-04-18 09:27:47 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

