<?php
require_once APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_Client_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_bot_telegram_client_id	= 'ID';
		$this->sys_bot_telegram_client_id_user	= 'ID_USER';
		$this->sys_bot_telegram_client_chat_id	= 'CHAT_ID';
		$this->sys_bot_telegram_client_register_date	= 'REGISTER_DATE';
		$this->sys_bot_telegram_client_register_time	= 'REGISTER_TIME';
		$this->sys_bot_telegram_client_status	= 'STATUS';
		$this->tuser_id	= 'TUSER_ID';
		$this->tuser_nmuser	= 'NMUSER';
		$this->tuser_passuser	= 'PASSUSER';
		$this->tuser_opt_level	= 'OPT_LEVEL';
		$this->tuser_opt_status	= 'OPT_STATUS';
		$this->tuser_picture	= 'PICTURE';
		$this->tuser_skin	= 'SKIN';
		$this->tstatus_id	= 'TSTATUS_ID';
		$this->tstatus_status	= 'TSTATUS_STATUS';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_id_user	= 'id_user';
		$this->f_chat_id	= 'chat_id';
		$this->f_register_date	= 'register_date';
		$this->f_register_time	= 'register_time';

		$this->f_nmuser	= 'nmuser';

		$this->f_tstatus_status	= 'status';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
		//	$this->f_id	=> $this->sys_bot_telegram_client_id,
		//	$this->f_id_user	=> $this->sys_bot_telegram_client_id_user,
			$this->f_nmuser	=> $this->tuser_nmuser,
			$this->f_chat_id	=> $this->sys_bot_telegram_client_chat_id,
			$this->f_register_date	=> $this->sys_bot_telegram_client_register_date,
			$this->f_register_time	=> $this->sys_bot_telegram_client_register_time,
			
		
			'tstatus'				=> 'STATUS',	
			
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-02-14 20:59:24 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

