<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Devauth_config {
	


   

   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_developer_id	= 'ID';
		$this->sys_developer_name	= 'REGISTER NAME';
		$this->sys_developer_email	= 'EMAIL';
		$this->sys_developer_host	= 'HOST';
		$this->sys_developer_id_dev	= 'ID-DEV';
		$this->sys_developer_app_name	= 'APP_NAME';
		$this->jumlah_otorisasi = "TOTAL OTORISASI";
		$this->send_documentation = "SEND DOCUMENTATION";
		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_name	= 'name';
		$this->f_email	= 'email';
		$this->f_host	= 'host';
		$this->f_id_dev	= 'id_dev';
		$this->f_app_name	= 'app_name';
		$this->f_key	= 'key';
		$this->f_send_activate	 = 'send_activate';
		$this->f_jumlah_otorisasi = "jumlah_otorisasi";
		$this->f_send_documentation = "send_documentation";
		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
	
			$this->f_name				=> $this->sys_developer_name,
			$this->f_id_dev				=> $this->sys_developer_id_dev,
			$this->f_email				=> $this->sys_developer_email,
			$this->f_jumlah_otorisasi	=> $this->jumlah_otorisasi,
			$this->f_send_documentation => $this->send_documentation,
			
		);

	}

};










/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-08-30 13:11:50 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

