<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Developer_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_developer_id	= 'ID';
		$this->sys_developer_name	= 'REGISTER NAME';
		$this->sys_developer_email	= 'EMAIL';
		$this->sys_developer_host	= 'HOST';
		$this->sys_developer_id_dev	= 'ID_DEV';
		$this->sys_developer_app_name	= 'APP_NAME';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_name	= 'name';
		$this->f_email	= 'email';
		$this->f_host	= 'host';
		$this->f_id_dev	= 'id_dev';
		$this->f_app_name	= 'app_name';
		$this->f_key	= 'key';
		$this->f_send_activate	 = 'send_activate';
		

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			//$this->f_id	=> $this->sys_developer_id,
			$this->f_id_dev	=> $this->sys_developer_id_dev,
			$this->f_key	=> "KEY",
			$this->f_name	=> $this->sys_developer_name,
			$this->f_email	=> $this->sys_developer_email,
			'status'		=> "STATUS",
			$this->f_send_activate => "SEND ACTIVATE",
			//$this->f_host	=> $this->sys_developer_host,
			//$this->f_app_name	=> $this->sys_developer_app_name,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-08-25 13:35:46 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

