<?php
require_once APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class GDriveCredential_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_gdrive_id	= 'ID';
		$this->sys_gdrive_path_credential	= 'PATH_CREDENTIAL';
		$this->sys_gdrive_status	= 'STATUS';
		$this->tstatus_id	= 'TSTATUS_ID';
		$this->tstatus_status	= 'STATUS';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_path_credential	= 'path_credential';
		$this->f_status	= 'status';
		$this->f_tstatus_id	= 'tstatus_id';
		$this->f_tstatus_status	= 'tstatus_status';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			//$this->f_id	=> $this->sys_gdrive_id,
			'account' => "Google Account",
			'descriptions' => "Descriptions",
			$this->f_path_credential	=> $this->sys_gdrive_path_credential,
		//	$this->f_status	=> $this->sys_gdrive_status,
			//$this->f_tstatus_id	=> $this->tstatus_id,
			$this->f_tstatus_status	=> $this->tstatus_status,
			'token_ready'=>'TOKEN STATUS',
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-07-04 12:04:25 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

