<?php
require_once APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class UploadFile_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_filesistem_id	= 'ID';
		$this->sys_filesistem_file	= 'FILE';
		$this->sys_filesistem_keterangan	= 'KETERANGAN';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_file	= 'file';
		$this->f_keterangan	= 'keterangan';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
		//	$this->f_id		=> $this->sys_filesistem_id,
			$this->f_file	=> $this->sys_filesistem_file,
			'orig_name'		=> "Orig Name",
			'path'			=> "Path",
			$this->f_keterangan	=> $this->sys_filesistem_keterangan,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-07-02 16:05:15 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

