<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_authorized_frontend_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->user_authorized_frontend_id	= 'ID';
		$this->user_authorized_frontend_link	= 'LINK';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_link	= 'link';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->user_authorized_frontend_id,
			$this->f_link	=> $this->user_authorized_frontend_link,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-03-10 08:48:28 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

