<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class DevauthModel extends CI_Model {
   public $id;	
  
 
   
   
   
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			sys_developer.id as id,
			sys_developer.id_dev,
			sys_developer.name as name,
			sys_developer.email as email,
			sys_developer.host as host,
			sys_developer.app_name as app_name,
			sys_developer.send_documentation as send_documentation,
			api_access.jumlah_otorisasi
		');
		
		$this->datatables->join('
			(SELECT 
			COUNT(sys_api_access.id) as jumlah_otorisasi,
			sys_api_access.key
			FROM 
			sys_api_access 
			GROUP BY sys_api_access.key)  api_access'
		,'api_access.key=sys_developer.id_dev','LEFT');
		
		$this->datatables->where("sys_developer.activate_at <>", null);
		$this->datatables->from('sys_developer');
		
		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

	
	
	

  


	public function get_by_id($id){
		$afield = array(
			'sys_developer.id as id',
			'sys_developer.key as key',
			'sys_developer.id_dev',
			'sys_developer.name as name',
			'sys_developer.email as email',
			'sys_developer.activate_at as active',
			'sys_developer.send_documentation as send_documentation',
			'sys_api_access.all_access as all_access',
			'sys_api_access.controller as controller',
			'sys_api_access.date_created as date_created',
			'sys_api_access.date_modified as date_modified',
			
			
		
		);
		$this->db->select($afield);

		$this->db->where('sys_developer.id', $id);
		$this->db->join("sys_api_access", "sys_api_access.key=sys_developer.id_dev","LEFT");
		$this->db->order_by('sys_api_access.id', 'ASC');
		return $this->db->get('sys_developer')->result();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('sys_api_access.id <>',$id);

		$q = $this->db->get_where('sys_api_access', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function updateSendEmail($id,$data){
		$this->db->trans_start();

		$this->db->where('sys_developer.id', $id);
		$this->db->update('sys_developer',$data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}


	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();
		
		$reset = [
			"send_documentation" => 0 ,
			"send_doc_at"	=> null,
		];
		
		$this->db->where('sys_developer.id_dev', $id);
		$this->db->update('sys_developer',$reset);

		$this->db->where('sys_api_access.key', $id);
		$this->db->delete('sys_api_access');
		
		$split = array_chunk($data,2);
		
		foreach($split as $val){
		
			$this->db->insert_batch('sys_api_access',$val);
		}
		
	
		
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}



};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-08-30 13:11:50 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
