<?php
namespace model\sys\api;

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use Illuminate\Database\Eloquent\Model as CI_Model;
//use Illuminate\Database\Capsule\Manager as DB;

class DeveloperModel extends CI_Model {
	
	protected $table="sys_developer";
	protected $fillable = [ "name" , "email" , "host" , "id_dev" , "app_name" ,	];
	const validation = [];

};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-08-25 13:35:46 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
