<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class ImportExcel_model extends CI_Model {
	
   function __construct(){
        parent::__construct();
   }
   
   
   
   	function insert_multiple($table,$data){
		$this->db->trans_start();

		 $this->db->insert_batch($table, $data);
		
		
		$this->db->trans_complete();
		return $this->db->trans_status();	
	}

    function getPrimaryName($table){
		$sql = "
			SHOW INDEX FROM $table WHERE Key_name = 'PRIMARY';
		";
		
		return $this->db->query($sql)->result()[0]->Column_name;
	}
	
	function reset_table($table){
		 $this->db->empty_table($table);
		 $this->db->query("ALTER TABLE $table AUTO_INCREMENT = 1");
	}
   
   
   
   
   
}


		
/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CLI 2021-03-11 11:49:11 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
	
