<?php

class Template_ORMmodel extends CI_Model {

function __construct(){
      parent::__construct();
}

function create_model($gf,$file_name,$path_model,
					  $field_alias_field,$table_join,$index_alias_table_join,
					  $table,$crud_show,$type_input_field){

$private_where="";
$private_ss_where="";
$private_insert="";
$private_id=""; 
$separator="";

$className = str_replace("_ORM","",$file_name);

if($crud_show=='off'){
	$private_id 		= "\$user_id";
	$private_where		= "		\$this->db->where('$table.user_input',\$user_id);";	
	$private_ss_where 	= "\$this->datatables->where('$table.user_input',\$user_id);";
	$private_insert		= " 	\$data['user_input'] = \$user_id;";
	$separator 			=  ",";
}					  
						  
$string = "<?php
namespace model\\".$gf.";

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use Illuminate\Database\Eloquent\Model as CI_Model;
//use Illuminate\Database\Capsule\Manager as DB;

class $className extends CI_Model {
	
	protected \$table=\"$table\";
	protected \$fillable = [";
  foreach($field_alias_field as $key=>$val){
	  if($val !=="id")
			$string .=	" \"$val\" ,";

  }	  

$string .="	];
	const validation = [];

};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator ".date('Y-m-d H:i:s')." */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
"	;	
		
		
$result = _createFile($string,$path_model,$file_name .'.php');		
return $result;		
		
}	
	
	
	
}	