<?php
class Template_controller_blank extends CI_Model {


function __construct(){
      parent::__construct();
	  
}




function create_controller($fc,$fm,$fl,$ff,$pc,$gf,
					  $field_alias_form,$field_alias_field,$type_input_field,
					  $field_double,$field_empty,
					  $crud_show,$server_side){

$private_where="";
$private_insert="";
$private_id=""; 
$separator="";

if($crud_show=='off'){
	$private_id 	= "\$this->_user_id";
	$separator =  ",";
}	
					  

$string = "<?php
require APPPATH. '/controllers/$gf/$fc"."_config.php';

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use ybs\general\Load;
use ybs\general\Validation;
use ybs\general\Storage;

use ybs\http\Request;
use ybs\http\Response;



//untuk menggunakan model Eloquent laravel aktifkan code di bawah ini//
//use model\\".$gf."\\" .$fm . ";


class $fc extends CI_Controller {
	
	private \$tmodel;
    public function __construct(){
        parent::__construct();
		
		 //use this for load all model in folder
		 Load::model(\"$gf\");
		 
		 \$this->tmodel =  new \\$fm();
		 
		 IDCoder::run(\$this);
    }

";

//----->function index <-------//  
$string .="
	public function index(){
		\$breadcrumb = [
			'$fc' 	=>   url(),
			'List Data' 		=>  '',
		];
		
		\$data = [
			'breadcrumb'			=> \$breadcrumb,
			'title_page_big'		=> 'Daftar $fc',
			'title'					=> new $fc"."_config(),
		];
		
		response()->view('$gf/$fl',\$data);

	}
";	
//----->END index <-------//  	



	
//end class		
$string .= "


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator ".date('Y-m-d H:i:s')." */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

"	;	
	
	
	
$this->create_config_file($fc,$fm,$fl,$ff,$pc,$gf,
					  $field_alias_form,$field_alias_field,$type_input_field,
					  $crud_show);
					  
$result = _createFile($string,$pc,$fc .'.php');		
return $result;			
	
}



function create_config_file($fc,$fm,$fl,$ff,$pc,$gf,
					  $field_alias_form,$field_alias_field,$type_input_field,
					  $crud_show){

$string = "<?php
require_once APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class $fc".'_config'." {
	

";



$string .="
   function __construct(){
	   /* title */
	    \$this->general		= new General_title();
";

foreach($field_alias_form as $key=>$val){
$keys = str_replace('.','_',$key);	
$string .="		\$this->$keys	= '$val';
";	
}

$string .="
		
		
		
		/*field_alias_database db*/
";	
foreach($field_alias_field as $key=>$val){
$keys = str_replace('.','_',$key);	
$string .="		\$this->f_$val	= '$val';
";	
}


$string .="
		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => \$title */	
		\$this->table_column =array(
";	
foreach($field_alias_field as $key=>$val){
$keys = str_replace('.','_',$key);	
$string .="			\$this->f_$val	=> \$this->$keys,
";	
}

$string .="		);
";




//end class		
$string .= "
	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator ".date('Y-m-d H:i:s')." */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

"	;	

$result =  _createFile($string,$pc,$fc .'_config.php');	
}











}
