<?php
namespace model\Sistemx;

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use Illuminate\Database\Eloquent\Model as CI_Model;
//use Illuminate\Database\Capsule\Manager as DB;

class UploadFileModel extends CI_Model {
	
	protected $table="sys_filesistem";
	protected $fillable = [ "file" , "keterangan" ,	];
	const validation = [];

};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-07-02 16:05:15 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
