<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class UploadFileModel extends CI_Model {
   public $id;	
   const table = "sys_filesistem";
   const rules = [
	"file" => "required",
	"keterangan" => "required",  
  ];
   
   
   
   function __construct(){
        parent::__construct();
   }	
	
	public function json( $apiPost=null){
		if($apiPost)
			$this->datatables->injectPost($apiPost);
		
		$this->datatables->select('
			sys_filesistem.id as id,
			sys_filesistem.file as file,
			CONCAT(sys_user_upload.file_path,sys_user_upload.name) as path,
			sys_user_upload.orig_name as orig_name,
		
			sys_filesistem.keterangan as keterangan,
		');

		if ($this->db->field_exists('delete_at', 'sys_filesistem')){
			$this->datatables->where('sys_filesistem.delete_at',null);
			
			$this->datatables->where_post();
			$this->datatables->or_where('sys_filesistem.delete_at','0000-00-00 00:00:00');
		}
		
		$this->datatables->join("sys_user_upload","sys_user_upload.time=sys_filesistem.file","LEFT");
		
		$this->datatables->from('sys_filesistem');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = [
			'sys_filesistem.id as id',
			'sys_filesistem.file as file',
			'sys_filesistem.keterangan as keterangan',
		
		];
		
		if ($this->db->field_exists('delete_at', 'sys_filesistem')){
			$this->db->where('sys_filesistem.delete_at',null);
			
			$this->db->or_where('sys_filesistem.delete_at','0000-00-00 00:00:00');
		}
		
		
		$this->db->select($afield);

		$this->db->order_by('sys_filesistem.id', 'ASC');
		return $this->db->get('sys_filesistem')->result_array();
   }


	public function get_by_id($id){
		$afield = [
			'sys_filesistem.id as id',
			'sys_filesistem.file as file',
			'sys_filesistem.keterangan as keterangan',
		
		];
		
		
		
		$this->db->select($afield);

		$this->db->where('sys_filesistem.id', $id);
		$this->db->order_by('sys_filesistem.id', 'ASC');
		return $this->db->get('sys_filesistem')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('sys_filesistem.id <>',$id);
		
		if ($this->db->field_exists('delete_at', 'sys_filesistem')){
			$this->db->where('sys_filesistem.delete_at',null);
			$this->db->or_where('sys_filesistem.delete_at','0000-00-00 00:00:00');
			$this->db->where('sys_filesistem.id <>',$id);
		}
		

		$q = $this->db->get_where('sys_filesistem', $data)->result_array();
		
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('sys_filesistem', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('sys_filesistem.id', $id);
		$this->db->update('sys_filesistem', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data,$permanent=true){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			if($permanent){
				$this->db->where_in('sys_filesistem.id',$data);	
		
				$this->db->delete('sys_filesistem');
			}else{
				$tm = Date('Y-m-d H:i:s',time());
				$this->db->where_in('sys_filesistem.id',$data);
				$this->db->update('sys_filesistem',['delete_at'=>$tm]);
			}	
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-07-02 16:05:15 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
